<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>x86</Platforms>
    <AssemblyName>PlusOneTrainer</AssemblyName>
    <RootNamespace>PlusOneTrainer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\plus-one.ico</ApplicationIcon>
    <Version>1.0.0-beta.3</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\sprout-mechanic.png" />
    <Resource Include="Assets\plus-one.ico" />
  </ItemGroup>
</Project>
